apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx 
  replicas: 5 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: server
          imagePullPolicy: IfNotPresent
          image: nginx-gh
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: nginx
  clusterIP: 10.96.1.1
